### ISSUE TITLE
Add some mRNAs to fsce_tidy

### ISSUE THREAD

**Issue by jayhesselberth** [hesselberthlab/scrunchy#32]
FTL

**Comment by mandylr** [comment]
These genes 


Markers | Cell Type
-- | --
IL7R | CD4 T cells
CD14, LYZ | CD14+ Monocytes
MS4A1 | B cells
CD8A | CD8 T cells
FCGR3A, MS4A7 | FCGR3A+ Monocytes
GNLY, NKG7 | NK cells
FCER1A, CST3 | Dendritic Cells
PPBP | Megakaryocytes
