### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by jayhesselberth** [hesselberthlab/scrunchy#4]
Doesn't really belong here. Put it in [rhumba](https://github.com/rnabioco/rhumba).

**Comment by mandylr** [comment]
mrna data: beevol/home/richerm/projects/10x_haircut/20181214/data/mrna
haircut data: beevol/home/richerm/projects/10x_haircut/20181214/data/haircut

There are two sets of haircut data in there that have all the same cell barcodes, but different library preps. Just use JH134_2

scripts: /beevol/home/richerm/projects/10x_haircut/20181214/scripts

1. extract cell barcode/umi: all_data.extract.sh
2. trim TSO and polyA : trim_all_all_data.sh
3. align: align_all.sh
4. Add hairpin and position to bam files: add_genes.py, 10x_make_fastq.sh
5. Count umis/gene: count.sh

**Comment by kriemo** [comment]
The pipeline, which is a work in progress is here:
https://github.com/rnabioco/rhumba/tree/master/haircut
